# Generated by Django 4.2.14 on 2025-10-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('normal', '正常'), ('fault', '故障'), ('offline', '离线')], default='normal', max_length=10)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
